### ISSUE TITLE
[BUG] Uncaught exception if provided bucket name doesn't exist

### ISSUE THREAD

**Issue by tomekit** [photosync/android-photosync-s3#3]
Fix will be released in 4th August evening release.

Log:
```
#### EXCEPTION UNCAUGHT EXCEPTION ####
java.util.NoSuchElementException: List is empty.
    at kotlin.collections.CollectionsKt___CollectionsKt.first(_Collections.kt:212)
    at com.syncsolutions.backblazesync.helper.BackblazeHelper.getBucketId(BackblazeHelper.kt:57)
    at com.syncsolutions.backblazesync.fragment.LandingLoginFragment$onCreateView$1$1$thread$1.run(LandingLoginFragment.kt:72)
#### EXCEPTION END ####
#### DEVICE
....
#### VERSION
Name: 1.2.2
Code: 10020290
Hash: 9c63f2d7ab78afa66ca5b9f83aa0f009a14d0361
SQLite version: 3.32.2
Date: 2022-08-01 16:31:18
```

**Comment by tomekit** [comment]
This is now resolved.
